### ISSUE TITLE
1.18

### ISSUE THREAD

**Issue by pozhiloy-enotik** [PrismarineJS/minecraft-data#476] opened 2021-12-04 19:16 UTC

**Comment by rom1504** [comment] 2021-12-04 19:51
Duplicate of #474

**Closed by rom1504** 2021-12-04 19:51 UTC

**Comment by SylveonBottle** [comment] 2021-12-08 20:17
Is this request for 1.18 bedrock, or java addition? 
Or does #474 also handle java edition as well?

I was going to make a suggestion for 1.18 java edition, but it appears that this was reported as duplicate.. of bedrock edition?

**Comment by rom1504** [comment] 2021-12-08 21:01
#474 is for mcpc
Bedrock 1.18 is already done

**Comment by SylveonBottle** [comment] 2021-12-08 21:49
So which issue is for java 1.18?

**Comment by rom1504** [comment] 2021-12-08 21:58
https://github.com/PrismarineJS/minecraft-data/issues/474
mcpc = java
