### ISSUE TITLE
Add durability and other extra info on Items and Blocks

### ISSUE THREAD

**Issue by MestreLion** [PrismarineJS/minecraft-data#256] opened 2019-11-21 05:11 UTC
Resuming the discussion that started at #254 with @timmyRS :

It would be wonderful if data could provide a little more information on each Block and Item type. The ones I miss the most are:

- Item **Durability**, integer: sometimes referred as "max damage", not to be confused with current damage of a particular item. How should I it integrate with `items.json`? An extra field for each item named `durability`? For items where durability does not apply, should it be `0`, `null` or not have the field?

 Here's the data as of 1.14.4:
```json
{
	"bow": 384,
	"carrot_on_a_stick": 25,
	"chainmail_boots": 195,
	"chainmail_chestplate": 240,
	"chainmail_helmet": 165,
	"chainmail_leggings": 225,
	"crossbow": 326,
	"diamond_axe": 1561,
	"diamond_boots": 429,
	"diamond_chestplate": 528,
	"diamond_helmet": 363,
	"diamond_hoe": 1561,
	"diamond_leggings": 495,
	"diamond_pickaxe": 1561,
	"diamond_shovel": 1561,
	"diamond_sword": 1561,
	"elytra": 432,
	"fishing_rod": 64,
	"flint_and_steel": 64,
	"golden_axe": 32,
	"golden_boots": 91,
	"golden_chestplate": 112,
	"golden_helmet": 77,
	"golden_hoe": 32,
	"golden_leggings": 105,
	"golden_pickaxe": 32,
	"golden_shovel": 32,
	"golden_sword": 32,
	"iron_axe": 250,
	"iron_boots": 195,
	"iron_chestplate": 240,
	"iron_helmet": 165,
	"iron_hoe": 250,
	"iron_leggings": 225,
	"iron_pickaxe": 250,
	"iron_shovel": 250,
	"iron_sword": 250,
	"leather_boots": 65,
	"leather_chestplate": 80,
	"leather_helmet": 55,
	"leather_leggings": 75,
	"shears": 238,
	"shield": 336,
	"stone_axe": 131,
	"stone_hoe": 131,
	"stone_pickaxe": 131,
	"stone_shovel": 131,
	"stone_sword": 131,
	"trident": 250,
	"wooden_axe": 59,
	"wooden_hoe": 59,
	"wooden_pickaxe": 59,
	"wooden_shovel": 59,
	"wooden_sword": 59
}
```

- Item **Placeable** (or **is/has_block**), boolean: If the item can (exist / be placed) in the world as a block (with the same ID, be it numerical or namespaced string). All items which prior to The Flattening had ID < 256 are placeable, all others are not, and a few introduced after 1.12 are too.

- Block **Obtainable** (or **is/has_item**), boolean: If the block is obtainable in item form. Most blocks are, exceptions are blocks such as `water`, `fire`, `air`, and blocks that change their ID when dropped, such as most crops (`carrots` become `carrot`), Walled blocks (Signs, Banners, Torch) etc.

**Comment by rom1504** [comment] 2020-05-09 09:52
duplicate of #212

**Closed by rom1504** 2020-05-09 09:52 UTC
