### ISSUE TITLE
VarInt vs VarLong : it is not differentiated in protocol

### ISSUE THREAD

**Issue by nicoxxl** [PrismarineJS/minecraft-data#543] opened 2022-04-23 15:26 UTC
In the [`pc/1.18.2/protocol.json`](https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.18.2/protocol.json), there is only `"varint"`.

On [wiki.vg](https://wiki.vg/Protocol), there is some packet that use `VarLong` but on the [definition](https://wiki.vg/Protocol#VarInt_and_VarLong), the same byte sequence could be decoded differently (see the samples).

**Comment by nickelpro** [comment] 2022-04-23 15:40
Duplicate of https://github.com/PrismarineJS/minecraft-data/issues/119

For the purposes of interpreting protocol.json, all varints should be considered varlongs. This is a non-issue because the difference is only visible when encoding negative values, which the protocol doesn't do at the moment.

Closing.

**Closed by nickelpro** 2022-04-23 15:40 UTC

**Comment by nicoxxl** [comment] 2022-04-23 15:46
My bad, sorry for the noise.
